version: '3'

services: 
  flask-api:
    image: flask-api
    container_name: flask-api
    build: ./flask
    volumes: 
    - ./flask:/usr/src/app/
    ports: 
    - 5000:5000
  nginx:
    image: nginx
    container_name: nginx
    volumes: 
    - ./nginx:/usr/share/nginx/html/
    ports:
    - "8080:80"
    # command: [nginx-debug, '-g', 'daemon off;']